<?php

/**
 * This class was autogenerated
 * Do NOT edit
 * Version: 2022/2023
 */

namespace ShooglyPeg\Teams;

use ShooglyPeg\Name;
use ShooglyPeg\Teams\Exceptions\InvalidTeamName;

final class TeamName extends Name
{
    public const ABERDEEN                     = 'Aberdeen';
    public const AIRDRIEONIANS                = 'Airdrieonians';
    public const ALBION_ROVERS                = 'Albion Rovers';
    public const ALLOA_ATHLETIC               = 'Alloa Athletic';
    public const ANNAN_ATHLETIC               = 'Annan Athletic';
    public const ARBROATH                     = 'Arbroath';
    public const AYR_UNITED                   = 'Ayr United';
    public const BONNYRIGG_ROSE_ATHLETIC      = 'Bonnyrigg Rose Athletic';
    public const BERWICK_RANGERS              = 'Berwick Rangers';
    public const BRECHIN_CITY                 = 'Brechin City';
    public const CELTIC                       = 'Celtic';
    public const CLYDE                        = 'Clyde';
    public const COVE_RANGERS                 = 'Cove Rangers';
    public const COWDENBEATH                  = 'Cowdenbeath';
    public const DUMBARTON                    = 'Dumbarton';
    public const DUNDEE                       = 'Dundee';
    public const DUNDEE_UNITED                = 'Dundee United';
    public const DUNFERMLINE_ATHLETIC         = 'Dunfermline Athletic';
    public const EAST_FIFE                    = 'East Fife';
    public const EAST_STIRLINGSHIRE           = 'East Stirlingshire';
    public const FC_EDINBURGH                 = 'FC Edinburgh';
    public const ELGIN_CITY                   = 'Elgin City';
    public const FALKIRK                      = 'Falkirk';
    public const FORFAR_ATHLETIC              = 'Forfar Athletic';
    public const GREENOCK_MORTON              = 'Greenock Morton';
    public const HAMILTON_ACADEMICAL          = 'Hamilton Academical';
    public const HEART_OF_MIDLOTHIAN          = 'Heart Of Midlothian';
    public const HIBERNIAN                    = 'Hibernian';
    public const INVERNESS_CALEDONIAN_THISTLE = 'Inverness Caledonian Thistle';
    public const KELTY_HEARTS                 = 'Kelty Hearts';
    public const KILMARNOCK                   = 'Kilmarnock';
    public const LIVINGSTON                   = 'Livingston';
    public const MONTROSE                     = 'Montrose';
    public const MOTHERWELL                   = 'Motherwell';
    public const PARTICK_THISTLE              = 'Partick Thistle';
    public const PETERHEAD                    = 'Peterhead';
    public const QUEEN_OF_THE_SOUTH           = 'Queen Of The South';
    public const QUEENS_PARK                  = 'Queen\'s Park';
    public const RAITH_ROVERS                 = 'Raith Rovers';
    public const RANGERS                      = 'Rangers';
    public const ROSS_COUNTY                  = 'Ross County';
    public const ST_JOHNSTONE                 = 'St Johnstone';
    public const ST_MIRREN                    = 'St Mirren';
    public const STENHOUSEMUIR                = 'Stenhousemuir';
    public const STIRLING_ALBION              = 'Stirling Albion';
    public const STRANRAER                    = 'Stranraer';

    private const VALID = [
        self::ABERDEEN,
        self::AIRDRIEONIANS,
        self::ALBION_ROVERS,
        self::ALLOA_ATHLETIC,
        self::ANNAN_ATHLETIC,
        self::ARBROATH,
        self::AYR_UNITED,
        self::BONNYRIGG_ROSE_ATHLETIC,
        self::BERWICK_RANGERS,
        self::BRECHIN_CITY,
        self::CELTIC,
        self::CLYDE,
        self::COVE_RANGERS,
        self::COWDENBEATH,
        self::DUMBARTON,
        self::DUNDEE,
        self::DUNDEE_UNITED,
        self::DUNFERMLINE_ATHLETIC,
        self::EAST_FIFE,
        self::EAST_STIRLINGSHIRE,
        self::FC_EDINBURGH,
        self::ELGIN_CITY,
        self::FALKIRK,
        self::FORFAR_ATHLETIC,
        self::GREENOCK_MORTON,
        self::HAMILTON_ACADEMICAL,
        self::HEART_OF_MIDLOTHIAN,
        self::HIBERNIAN,
        self::INVERNESS_CALEDONIAN_THISTLE,
        self::KELTY_HEARTS,
        self::KILMARNOCK,
        self::LIVINGSTON,
        self::MONTROSE,
        self::MOTHERWELL,
        self::PARTICK_THISTLE,
        self::PETERHEAD,
        self::QUEEN_OF_THE_SOUTH,
        self::QUEENS_PARK,
        self::RAITH_ROVERS,
        self::RANGERS,
        self::ROSS_COUNTY,
        self::ST_JOHNSTONE,
        self::ST_MIRREN,
        self::STENHOUSEMUIR,
        self::STIRLING_ALBION,
        self::STRANRAER,
    ];

    private const NONLEAGUE = [self::BERWICK_RANGERS, self::COWDENBEATH, self::EAST_STIRLINGSHIRE];

    private const SHORT = [
        'Airdrie'        => self::AIRDRIEONIANS,
        'Albion'         => self::ALBION_ROVERS,
        'Alloa'          => self::ALLOA_ATHLETIC,
        'Annan'          => self::ANNAN_ATHLETIC,
        'Ayr'            => self::AYR_UNITED,
        'Bonnyrigg'      => self::BONNYRIGG_ROSE_ATHLETIC,
        'Berwick'        => self::BERWICK_RANGERS,
        'Brechin'        => self::BRECHIN_CITY,
        'Cove'           => self::COVE_RANGERS,
        'Dundee Utd'     => self::DUNDEE_UNITED,
        'Dunfermline'    => self::DUNFERMLINE_ATHLETIC,
        'East Stirling'  => self::EAST_STIRLINGSHIRE,
        'Edinburgh City' => self::FC_EDINBURGH,
        'Elgin'          => self::ELGIN_CITY,
        'Forfar'         => self::FORFAR_ATHLETIC,
        'Morton'         => self::GREENOCK_MORTON,
        'Hamilton'       => self::HAMILTON_ACADEMICAL,
        'Hearts'         => self::HEART_OF_MIDLOTHIAN,
        'Inverness CT'   => self::INVERNESS_CALEDONIAN_THISTLE,
        'Kelty'          => self::KELTY_HEARTS,
        'Partick'        => self::PARTICK_THISTLE,
        'Queen of Sth'   => self::QUEEN_OF_THE_SOUTH,
        'Queen\'s Pk'    => self::QUEENS_PARK,
        'Raith'          => self::RAITH_ROVERS,
        'Stirling'       => self::STIRLING_ALBION,
    ];

    public const TYPOS = [
        'Airdrie United'      => self::AIRDRIEONIANS,
        'Ayr Utd'             => self::AYR_UNITED,
        'Heart OF Midlothian' => self::HEART_OF_MIDLOTHIAN,
        'Queen of the South'  => self::QUEEN_OF_THE_SOUTH,
        'Queen of South'      => self::QUEEN_OF_THE_SOUTH,
        'Queens Park'         => self::QUEENS_PARK,
        'ST Johnstone'        => self::ST_JOHNSTONE,
        'ST Mirren'           => self::ST_MIRREN,
    ];

    public function __construct(string $name)
    {
        if (!in_array($name, self::VALID)) {
            $alt = self::TYPOS[$name] ?? self::SHORT[$name] ?? null;
            if (!$alt) {
                throw InvalidTeamName::fromValue($name);
            } else {
                $name = $alt;
            }
        }

        $this->value = $name;
    }

    public function short(): string
    {
        return array_flip(self::SHORT)[$this->value] ?? $this->value;
    }

    public static function random(): TeamName
    {
        return new TeamName(self::VALID[array_rand(self::VALID)]);
    }

    public static function league(): array
    {
        return array_map(fn (string $name) => new TeamName($name), array_diff(self::VALID, self::NONLEAGUE));
    }

    public static function all(): array
    {
        return array_map(fn (string $name) => new TeamName($name), self::VALID);
    }
}
